//! L3 persona generation and the five-condition trigger.

use crate::AeonMemoryResult;
use crate::pipeline::checkpoint::{mutate_checkpoint, read_checkpoint};
use crate::scene::{generate_scene_navigation, read_scene_index, strip_scene_navigation};
use crate::types::{FileToolPolicy, LlmRunParams, LlmRunner};
use crate::utils::time::now_instant_iso;
use std::path::{Path, PathBuf};

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct TriggerResult {
    pub should: bool,
    pub reason: String,
}
pub struct PersonaTrigger {
    pub data_dir: PathBuf,
    pub interval: u64,
}
impl PersonaTrigger {
    pub fn should_generate(&self) -> AeonMemoryResult<TriggerResult> {
        let cp = read_checkpoint(self.data_dir.to_str().unwrap())?;
        let yes = |reason: &str| TriggerResult {
            should: true,
            reason: reason.into(),
        };
        if cp.request_persona_update {
            return Ok(yes(&format!(
                "主动请求: {}",
                if cp.persona_update_reason.is_empty() {
                    "Agent 请求更新"
                } else {
                    &cp.persona_update_reason
                }
            )));
        }
        let scenes = has_scene_files(&self.data_dir);
        if cp.scenes_processed > 0 && cp.last_persona_at == 0 && scenes {
            return Ok(yes("首次冷启动：首次提取完成且有场景文件"));
        }
        if cp.last_persona_at > 0 && scenes && !has_persona_body(&self.data_dir) {
            return Ok(yes("恢复：persona.md 正文丢失或为空，需要重新生成"));
        }
        if cp.scenes_processed == 1 && cp.memories_since_last_persona > 0 {
            return Ok(yes("首次 Scene Block 提取完成"));
        }
        if cp.memories_since_last_persona >= self.interval {
            return Ok(yes(&format!(
                "达到阈值: {} >= {}",
                cp.memories_since_last_persona, self.interval
            )));
        }
        Ok(TriggerResult {
            should: false,
            reason: String::new(),
        })
    }
}
fn has_scene_files(d: &Path) -> bool {
    std::fs::read_dir(d.join("scene_blocks"))
        .map(|i| {
            i.flatten()
                .any(|e| e.file_name().to_string_lossy().ends_with(".md"))
        })
        .unwrap_or(false)
}
fn has_persona_body(d: &Path) -> bool {
    std::fs::read_to_string(d.join("persona.md"))
        .map(|s| !strip_scene_navigation(&s).trim().is_empty())
        .unwrap_or(false)
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PersonaMode {
    First,
    Incremental,
}
pub struct PersonaPromptParams<'a> {
    pub mode: PersonaMode,
    pub current_time: &'a str,
    pub total_processed: u64,
    pub scene_count: usize,
    pub changed_scene_count: usize,
    pub changed_scenes_content: &'a str,
    pub existing_persona: Option<&'a str>,
    pub trigger_info: Option<&'a str>,
}
pub struct PersonaPrompt {
    pub system_prompt: String,
    pub user_prompt: String,
}

// Generated byte-for-byte from src/core/prompts/persona-generation.ts.
pub const PERSONA_SYSTEM_PROMPT: &str = include_str!("prompt/resources/persona_generation.txt");

pub fn build_persona_prompt(p: &PersonaPromptParams<'_>) -> PersonaPrompt {
    let label = if p.mode == PersonaMode::First {
        "🆕 首次生成"
    } else {
        "🔄 迭代更新"
    };
    let trigger = p
        .trigger_info
        .map(|x| format!("\n### 触发信息\n{x}\n"))
        .unwrap_or_default();
    let existing=p.existing_persona.map(|x|format!("\n## 📄 当前 Persona（工程已预加载）\n\n*以下是现有 persona.md 的完整内容（{} 字符），基于此更新后请控制在2000字内：*\n\n```markdown\n{x}\n```\n\n---\n",x.chars().count())).unwrap_or_default();
    let guide = if p.mode == PersonaMode::Incremental {
        "\n## 🔄 迭代决策指南\n\n面对变化场景，自主判断处理方式：强化（佐证已有洞察）/ 补充（新维度）/ 修正（矛盾）/ 重构（结构调整）/ 不改（无有用新增内容）。\n"
    } else {
        ""
    };
    let user_prompt = format!(
        "**Output language**: `persona.md` headings and body text must use the dominant language of the changed scene content below. For English scene content, use English persona headings.\n\n**⏰ 更新时间**: {}\n**模式**: {}\n{}\n## 📊 统计\n- **总记忆数**: {} 条\n- **场景总数**: {} 个\n- **变化场景**: {} 个（自上次更新后）\n\n---\n{}\n\n{}\n{}",
        p.current_time,
        label,
        trigger,
        p.total_processed,
        p.scene_count,
        p.changed_scene_count,
        p.changed_scenes_content,
        existing,
        guide
    );
    PersonaPrompt {
        system_prompt: PERSONA_SYSTEM_PROMPT.into(),
        user_prompt,
    }
}

pub struct PersonaGenerator<'a> {
    pub data_dir: PathBuf,
    pub runner: &'a dyn LlmRunner,
    pub backup_count: usize,
}
impl PersonaGenerator<'_> {
    pub async fn generate_local_persona(&self, reason: Option<&str>) -> AeonMemoryResult<bool> {
        let cp = read_checkpoint(self.data_dir.to_str().unwrap())?;
        let persona_path = self.data_dir.join("persona.md");
        let existing = std::fs::read_to_string(&persona_path)
            .ok()
            .map(|s| strip_scene_navigation(&s).trim().to_string())
            .filter(|s| !s.is_empty());
        let index = read_scene_index(&self.data_dir);
        let changed = index
            .iter()
            .filter(|e| {
                cp.last_persona_time.is_empty()
                    || date_ms(&e.updated)
                        .zip(date_ms(&cp.last_persona_time))
                        .map(|(a, b)| a > b)
                        .unwrap_or(true)
            })
            .collect::<Vec<_>>();
        let mut blocks = vec![];
        for e in &changed {
            if let Ok(raw) =
                std::fs::read_to_string(self.data_dir.join("scene_blocks").join(&e.filename))
            {
                blocks.push(format!(
                    "### [{}] {}\n\n```markdown\n{}\n```",
                    blocks.len() + 1,
                    e.filename,
                    raw
                ))
            }
        }
        if blocks.is_empty() && existing.is_some() {
            return Ok(false);
        }
        let changed_content = if blocks.is_empty() {
            "\n\n⚠️ **无变化场景**：所有场景均已在上次 Persona 更新中分析过，本次可直接读取所有场景进行全局审视。\n".into()
        } else {
            format!(
                "\n\n## 📄 变化场景完整内容\n\n*自上次 Persona 更新后，以下 {} 个场景发生了变化。工程已为你预加载完整内容：*\n\n{}\n\n---\n\n⚠️ **重点分析变化场景**：上述场景是自上次更新后的**新增/修改内容**，请**重点分析**这些场景中的新信息。\n",
                blocks.len(),
                blocks.join("\n\n")
            )
        };
        backup_file(
            &persona_path,
            &self.data_dir.join(".backup"),
            cp.total_processed,
            self.backup_count,
        )?;
        let prompt = build_persona_prompt(&PersonaPromptParams {
            mode: if existing.is_some() {
                PersonaMode::Incremental
            } else {
                PersonaMode::First
            },
            current_time: &now_instant_iso(),
            total_processed: cp.total_processed,
            scene_count: index.len(),
            changed_scene_count: changed.len(),
            changed_scenes_content: &changed_content,
            existing_persona: existing.as_deref(),
            trigger_info: reason,
        });
        if self
            .runner
            .run(LlmRunParams {
                prompt: prompt.user_prompt,
                system_prompt: Some(prompt.system_prompt),
                task_id: "persona-generation".into(),
                timeout_ms: Some(180_000),
                max_tokens: None,
                workspace_dir: Some(self.data_dir.to_string_lossy().into_owned()),
                file_tool_policy: Some(FileToolPolicy::Persona),
                instance_id: None,
            })
            .await
            .is_err()
        {
            // The TypeScript generator is fail-soft here: the pre-run backup
            // is retained, but any partial persona write is intentionally not
            // restored and the caller receives `false`.
            return Ok(false);
        }
        let raw = match std::fs::read_to_string(&persona_path) {
            Ok(v) => v,
            Err(_) => return Ok(false),
        };
        let body = escape_xml_tags(strip_scene_navigation(&raw).trim());
        if body.is_empty() {
            return Ok(false);
        }
        let nav = generate_scene_navigation(&index, None);
        std::fs::write(
            &persona_path,
            if nav.is_empty() {
                body
            } else {
                format!("{body}\n\n{nav}\n")
            },
        )?;
        Ok(true)
    }
    pub async fn generate(&self, reason: Option<&str>) -> AeonMemoryResult<bool> {
        if !self.generate_local_persona(reason).await? {
            return Ok(false);
        }
        let total = read_checkpoint(self.data_dir.to_str().unwrap())?.total_processed;
        mutate_checkpoint(self.data_dir.to_str().unwrap(), |cp| {
            cp.last_persona_at = total as i64;
            cp.last_persona_time = now_instant_iso();
            cp.memories_since_last_persona = 0;
            cp.request_persona_update = false;
            cp.persona_update_reason.clear();
        })?;
        Ok(true)
    }
}
fn date_ms(s: &str) -> Option<i64> {
    chrono::DateTime::parse_from_rfc3339(s)
        .ok()
        .map(|d| d.timestamp_millis())
}
fn backup_file(path: &Path, dir: &Path, offset: u64, keep: usize) -> AeonMemoryResult<()> {
    if !path.exists() {
        return Ok(());
    }
    let category = dir.join("persona");
    std::fs::create_dir_all(&category)?;
    let target = category.join(format!(
        "persona_{}_offset{offset}.md",
        chrono::Local::now().format("%Y%m%d_%H%M%S")
    ));
    std::fs::copy(path, target)?;
    let mut v = std::fs::read_dir(&category)?
        .flatten()
        .filter(|e| e.path().is_file())
        .collect::<Vec<_>>();
    v.sort_by_key(|e| e.file_name());
    if keep > 0 {
        while v.len() > keep {
            std::fs::remove_file(v.remove(0).path())?
        }
    }
    Ok(())
}
fn escape_xml_tags(s: &str) -> String {
    let mut out = s.to_string();
    for tag in [
        "user-persona",
        "relevant-memories",
        "scene-navigation",
        "relevant-scenes",
        "memory-tools-guide",
        "system",
        "assistant",
    ] {
        for p in [format!("<{tag}>"), format!("</{tag}>")] {
            out = out.replace(&p, &p.replace('<', "&lt;").replace('>', "&gt;"))
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::pipeline::checkpoint::{Checkpoint, write_checkpoint};
    fn dir(n: &str) -> PathBuf {
        let d = std::env::temp_dir().join(format!("aeon-memory-persona-{n}"));
        let _ = std::fs::remove_dir_all(&d);
        std::fs::create_dir_all(d.join("scene_blocks")).unwrap();
        d
    }
    #[test]
    fn trigger_priority() {
        let d = dir("trigger");
        std::fs::write(d.join("scene_blocks/a.md"), "x").unwrap();
        write_checkpoint(
            d.to_str().unwrap(),
            &Checkpoint {
                request_persona_update: true,
                persona_update_reason: "why".into(),
                scenes_processed: 1,
                ..Default::default()
            },
        )
        .unwrap();
        let r = PersonaTrigger {
            data_dir: d,
            interval: 10,
        }
        .should_generate()
        .unwrap();
        assert_eq!(
            r,
            TriggerResult {
                should: true,
                reason: "主动请求: why".into()
            }
        )
    }
    #[test]
    fn prompt_golden() {
        let p = build_persona_prompt(&PersonaPromptParams {
            mode: PersonaMode::First,
            current_time: "T",
            total_processed: 3,
            scene_count: 2,
            changed_scene_count: 1,
            changed_scenes_content: "SCENES",
            existing_persona: None,
            trigger_info: Some("R"),
        });
        assert!(p.user_prompt.contains(
            "**模式**: 🆕 首次生成\n\n### 触发信息\nR\n\n## 📊 统计\n- **总记忆数**: 3 条"
        ));
        assert!(p.user_prompt.ends_with("SCENES\n\n\n"));
    }

    struct PersonaWritingMock;
    #[async_trait::async_trait]
    impl LlmRunner for PersonaWritingMock {
        async fn run(&self, params: LlmRunParams) -> AeonMemoryResult<String> {
            assert_eq!(params.task_id, "persona-generation");
            assert_eq!(params.timeout_ms, Some(180_000));
            assert!(params.prompt.contains("### [1] scene.md"));
            std::fs::write(
                PathBuf::from(params.workspace_dir.unwrap()).join("persona.md"),
                "# User Narrative Profile\n\n</user-persona>",
            )?;
            Ok(String::new())
        }
    }

    #[tokio::test]
    async fn generator_file_golden() {
        let d = dir("generator");
        std::fs::create_dir_all(d.join(".metadata")).unwrap();
        std::fs::write(d.join("scene_blocks/scene.md"), "SCENE").unwrap();
        crate::scene::write_scene_index(
            &d,
            &[crate::scene::SceneIndexEntry {
                filename: "scene.md".into(),
                summary: "summary".into(),
                heat: 3,
                created: "2026-01-01T00:00:00Z".into(),
                updated: "2026-01-02T00:00:00Z".into(),
            }],
        )
        .unwrap();
        write_checkpoint(
            d.to_str().unwrap(),
            &Checkpoint {
                total_processed: 8,
                ..Default::default()
            },
        )
        .unwrap();
        let generator = PersonaGenerator {
            data_dir: d.clone(),
            runner: &PersonaWritingMock,
            backup_count: 3,
        };
        assert!(generator.generate(Some("reason")).await.unwrap());
        let output = std::fs::read_to_string(d.join("persona.md")).unwrap();
        assert!(output.starts_with(
            "# User Narrative Profile\n\n&lt;/user-persona&gt;\n\n---\n## 🗺️ Scene Navigation"
        ));
        assert!(output.contains("### Path: scene_blocks/scene.md"));
        let cp = read_checkpoint(d.to_str().unwrap()).unwrap();
        assert_eq!(cp.last_persona_at, 8);
        assert_eq!(cp.memories_since_last_persona, 0);
    }

    #[test]
    fn backup_layout_pruning_and_unlimited_match_backup_manager() {
        let dir = std::env::temp_dir().join(format!(
            "aeon-memory-persona-backup-manager-{}",
            std::process::id()
        ));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        let persona = dir.join("persona.md");
        let root = dir.join(".backup");
        let category = root.join("persona");
        std::fs::write(&persona, "current").unwrap();
        std::fs::create_dir_all(&category).unwrap();
        std::fs::write(category.join("persona_20260101_000000_offset0.md"), "old0").unwrap();
        std::fs::write(category.join("persona_20260101_000001_offset1.md"), "old1").unwrap();
        backup_file(&persona, &root, 2, 2).unwrap();
        assert_eq!(std::fs::read_dir(&category).unwrap().count(), 2);
        backup_file(&persona, &root, 3, 0).unwrap();
        assert_eq!(std::fs::read_dir(&category).unwrap().count(), 3);
        let _ = std::fs::remove_dir_all(dir);
    }
}
