use aeon_memory_core::config::{GatewayConfig, RecallStrategy};
use aeon_memory_core::pipeline::checkpoint::read_checkpoint;
use aeon_memory_core::types::{IMemoryStore, L1QueryFilter};
use aeon_memory_gateway::{
    AeonMemoryService, AppConfig, app,
    runtime::build_core,
    service::{
        BeforePromptRequest, CaptureRequest, ConversationSearchRequest, RecallRequest, SeedRequest,
        SessionEndRequest,
    },
};
use tower::ServiceExt;

async fn read_http_request(stream: &mut tokio::net::TcpStream) -> Vec<u8> {
    use tokio::io::AsyncReadExt;
    let mut bytes = Vec::new();
    let mut chunk = [0_u8; 4096];
    loop {
        let read = stream.read(&mut chunk).await.unwrap_or_default();
        if read == 0 {
            break;
        }
        bytes.extend_from_slice(&chunk[..read]);
        let Some(headers_end) = bytes.windows(4).position(|part| part == b"\r\n\r\n") else {
            continue;
        };
        let headers = String::from_utf8_lossy(&bytes[..headers_end]);
        let content_length = headers.lines().find_map(|line| {
            let (name, value) = line.split_once(':')?;
            name.eq_ignore_ascii_case("content-length")
                .then(|| value.trim().parse::<usize>().ok())
                .flatten()
        });
        if content_length.is_none_or(|length| bytes.len() >= headers_end + 4 + length) {
            break;
        }
    }
    bytes
}

async fn task_aware_llm_server() -> (String, std::sync::Arc<std::sync::Mutex<Vec<String>>>) {
    let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
    let address = listener.local_addr().unwrap();
    let events = std::sync::Arc::new(std::sync::Mutex::new(Vec::new()));
    let recorded = events.clone();
    tokio::spawn(async move {
        loop {
            let Ok((mut stream, _)) = listener.accept().await else {
                break;
            };
            let recorded = recorded.clone();
            tokio::spawn(async move {
                use tokio::io::AsyncWriteExt;
                let request = read_http_request(&mut stream).await;
                let request = String::from_utf8_lossy(&request);
                let (task, content) = if request.contains("Memory Consolidation Architect") {
                    ("l2", r#"{"scenes":[]}"#)
                } else if request.contains("Persona Architect") {
                    ("l3", "# Test Persona\n\nGenerated by deterministic mock.")
                } else if request.contains("记忆冲突检测器") {
                    ("dedup", "[]")
                } else {
                    (
                        "l1",
                        r#"[{"scene_name":"Differential Test Scene","message_ids":["l0_mock"],"memories":[{"content":"用户希望优化数据库查询性能","type":"episodic","priority":80,"source_message_ids":["l0_mock"],"metadata":{}}]}]"#,
                    )
                };
                recorded.lock().unwrap().push(task.into());
                let body = serde_json::json!({
                    "choices": [{"message": {"role": "assistant", "content": content}}]
                })
                .to_string();
                let response = format!(
                    "HTTP/1.1 200 OK\r\ncontent-type: application/json\r\ncontent-length: {}\r\nconnection: close\r\n\r\n{}",
                    body.len(),
                    body
                );
                let _ = stream.write_all(response.as_bytes()).await;
            });
        }
    });
    (format!("http://{address}/v1"), events)
}

async fn model_routing_llm_server() -> (
    String,
    std::sync::Arc<std::sync::Mutex<Vec<(String, String)>>>,
) {
    let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
    let address = listener.local_addr().unwrap();
    let events = std::sync::Arc::new(std::sync::Mutex::new(Vec::new()));
    let recorded = events.clone();
    tokio::spawn(async move {
        loop {
            let Ok((mut stream, _)) = listener.accept().await else {
                break;
            };
            let recorded = recorded.clone();
            tokio::spawn(async move {
                use tokio::io::AsyncWriteExt;
                let request = read_http_request(&mut stream).await;
                let request_text = String::from_utf8_lossy(&request);
                let body_text = request_text.split("\r\n\r\n").nth(1).unwrap_or("{}");
                let request_json: serde_json::Value = serde_json::from_str(body_text).unwrap();
                let model = request_json["model"].as_str().unwrap_or("").to_owned();
                let has_tool_result = request_json["messages"].as_array().is_some_and(|messages| {
                    messages.iter().any(|message| message["role"] == "tool")
                });
                let (task, message) = if request_text.contains("Memory Consolidation Architect") {
                    if has_tool_result {
                        (
                            "scene",
                            serde_json::json!({"role":"assistant","content":"{}"}),
                        )
                    } else {
                        (
                            "scene",
                            serde_json::json!({"role":"assistant","content":null,"tool_calls":[{"id":"scene-write","type":"function","function":{"name":"write_to_file","arguments":"{\"path\":\"routing.md\",\"content\":\"# Routing\\n\\nModel routing scene.\"}"}}]}),
                        )
                    }
                } else if request_text.contains("Persona Architect") {
                    if has_tool_result {
                        (
                            "persona",
                            serde_json::json!({"role":"assistant","content":"done"}),
                        )
                    } else {
                        (
                            "persona",
                            serde_json::json!({"role":"assistant","content":null,"tool_calls":[{"id":"persona-write","type":"function","function":{"name":"write_to_file","arguments":"{\"path\":\"persona.md\",\"content\":\"# Routed Persona\\n\\nModel C.\"}"}}]}),
                        )
                    }
                } else if request_text.contains("记忆冲突检测器") {
                    (
                        "dedup",
                        serde_json::json!({"role":"assistant","content":"[]"}),
                    )
                } else {
                    (
                        "l1",
                        serde_json::json!({"role":"assistant","content":r#"[{"scene_name":"routing","message_ids":["m"],"memories":[{"content":"routed memory","type":"episodic","priority":80,"source_message_ids":["m"],"metadata":{}}]}]"#}),
                    )
                };
                recorded.lock().unwrap().push((task.into(), model));
                let body = serde_json::json!({"choices":[{"message":message}]}).to_string();
                let response = format!(
                    "HTTP/1.1 200 OK\r\ncontent-type: application/json\r\ncontent-length: {}\r\nconnection: close\r\n\r\n{}",
                    body.len(),
                    body
                );
                let _ = stream.write_all(response.as_bytes()).await;
            });
        }
    });
    (format!("http://{address}/v1"), events)
}

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn scoped_models_route_l1_scene_persona_and_seed_override_independently() {
    let root =
        std::env::temp_dir().join(format!("aeon-memory-model-routing-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&root);
    let (url, events) = model_routing_llm_server().await;
    let mut config = GatewayConfig::default();
    config.data.base_dir = root.to_string_lossy().into_owned();
    config.llm.base_url = url;
    config.llm.api_key = "test".into();
    config.llm.model = "model-a".into();
    config.memory.embedding.enabled = false;
    config.memory.extraction.model = Some("provider/model-b".into());
    config.memory.persona.model = Some("provider/model-c".into());
    config.memory.pipeline.enable_warmup = true;
    config.memory.pipeline.l2_delay_after_l1_seconds = 0;
    config.memory.persona.trigger_every_n = 1;
    let service = build_core(&config).await.unwrap();
    service
        .capture(CaptureRequest {
            user_content: "route models".into(),
            assistant_content: "ack".into(),
            session_key: "routing-live".into(),
            session_id: Some("round".into()),
            user_id: None,
            messages: None,
        })
        .await
        .unwrap();
    service
        .end_session(SessionEndRequest {
            session_key: "routing-live".into(),
            user_id: None,
        })
        .await
        .unwrap();
    tokio::time::sleep(std::time::Duration::from_millis(250)).await;
    service.seed(SeedRequest {
        data: serde_json::json!({"sessions":[{"sessionKey":"routing-seed","sessionId":"round","conversations":[[{"role":"user","content":"seed route","timestamp":1783900000000_i64},{"role":"assistant","content":"ack","timestamp":1783900000001_i64}]]}]}),
        session_key: None, strict_round_role: None, auto_fill_timestamps: Some(true),
        config_override: Some(serde_json::json!({
            "extraction":{"model":"provider/model-b-seed"},
            "persona":{"model":"provider/model-c-seed","triggerEveryN":1},
            "pipeline":{"enableWarmup":true,"everyNConversations":1}
        }).as_object().unwrap().clone()),
    }).await.unwrap();
    service.shutdown().await.unwrap();
    let routed = events.lock().unwrap().clone();
    for (task, model) in [
        ("l1", "model-b"),
        ("scene", "model-b"),
        ("persona", "model-c"),
        ("l1", "model-b-seed"),
        ("scene", "model-b-seed"),
    ] {
        assert!(
            routed
                .iter()
                .any(|(actual_task, actual_model)| actual_task == task && actual_model == model),
            "missing {task}/{model}: {routed:?}"
        );
    }
    assert!(root.join("persona.md").is_file());
    let _ = std::fs::remove_dir_all(root);
}

async fn llm_server() -> String {
    llm_server_with("[]").await
}

async fn llm_server_with(content: &'static str) -> String {
    let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
    let address = listener.local_addr().unwrap();
    tokio::spawn(async move {
        loop {
            let Ok((mut stream, _)) = listener.accept().await else {
                break;
            };
            tokio::spawn(async move {
                use tokio::io::AsyncWriteExt;
                let _ = read_http_request(&mut stream).await;
                let body = serde_json::json!({
                    "choices": [{"message": {"content": content}}]
                })
                .to_string();
                let response = format!(
                    "HTTP/1.1 200 OK\r\ncontent-type: application/json\r\ncontent-length: {}\r\nconnection: close\r\n\r\n{}",
                    body.len(),
                    body
                );
                let _ = stream.write_all(response.as_bytes()).await;
            });
        }
    });
    format!("http://{address}/v1")
}

async fn delayed_embedding_server(delay_ms: u64) -> String {
    let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
    let address = listener.local_addr().unwrap();
    tokio::spawn(async move {
        loop {
            let Ok((mut stream, _)) = listener.accept().await else {
                break;
            };
            tokio::spawn(async move {
                use tokio::io::AsyncWriteExt;
                let _ = read_http_request(&mut stream).await;
                tokio::time::sleep(std::time::Duration::from_millis(delay_ms)).await;
                let body = r#"{"data":[{"index":0,"embedding":[1,0,0]}]}"#;
                let response = format!(
                    "HTTP/1.1 200 OK\r\ncontent-type: application/json\r\ncontent-length: {}\r\nconnection: close\r\n\r\n{}",
                    body.len(),
                    body
                );
                let _ = stream.write_all(response.as_bytes()).await;
            });
        }
    });
    format!("http://{address}")
}

async fn recording_embedding_server() -> (String, std::sync::Arc<std::sync::Mutex<Vec<String>>>) {
    let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
    let address = listener.local_addr().unwrap();
    let requests = std::sync::Arc::new(std::sync::Mutex::new(Vec::new()));
    let recorded = requests.clone();
    tokio::spawn(async move {
        loop {
            let Ok((mut stream, _)) = listener.accept().await else {
                break;
            };
            let recorded = recorded.clone();
            tokio::spawn(async move {
                use tokio::io::AsyncWriteExt;
                let request = read_http_request(&mut stream).await;
                recorded
                    .lock()
                    .unwrap()
                    .push(String::from_utf8(request).unwrap());
                let body = r#"{"data":[{"index":0,"embedding":[1,0,0]}]}"#;
                let response = format!(
                    "HTTP/1.1 200 OK\r\ncontent-type: application/json\r\ncontent-length: {}\r\nconnection: close\r\n\r\n{}",
                    body.len(),
                    body
                );
                let _ = stream.write_all(response.as_bytes()).await;
            });
        }
    });
    (format!("http://{address}"), requests)
}

#[tokio::test]
async fn production_offload_http_route_persists_real_l1_entry() {
    let root = std::env::temp_dir().join(format!(
        "aeon-memory-offload-route-e2e-{}",
        std::process::id()
    ));
    let _ = std::fs::remove_dir_all(&root);
    let llm_content =
        r#"[{"tool_call_id":"call-1","tool_call":"shell","summary":"listed files","score":8}]"#;
    let mut config = GatewayConfig::default();
    config.data.base_dir = root.to_string_lossy().into_owned();
    config.llm.base_url = llm_server_with(llm_content).await;
    config.llm.api_key = "test-key".into();
    config.llm.model = "test-model".into();
    config.memory.embedding.enabled = false;
    config.memory.offload.enabled = true;
    config.memory.offload.data_dir = Some(root.join("offload").to_string_lossy().into_owned());
    config.memory.offload.force_trigger_threshold = 1;
    let service = build_core(&config).await.unwrap();
    let router = app(service, AppConfig::default());
    let request = axum::http::Request::builder()
        .method("POST")
        .uri("/offload/after-tool")
        .header("content-type", "application/json")
        .body(axum::body::Body::from(
            serde_json::json!({
                "agent_id": "agent-e2e",
                "session_id": "session-e2e",
                "tool": {
                    "toolName": "shell",
                    "toolCallId": "call-1",
                    "params": {"cmd": "ls"},
                    "result": "file.txt",
                    "error": null,
                    "timestamp": "2026-07-13T00:00:00Z",
                    "durationMs": 5
                },
                "messages": [],
                "context_window": 1000
            })
            .to_string(),
        ))
        .unwrap();
    let response = router.oneshot(request).await.unwrap();
    assert_eq!(response.status(), axum::http::StatusCode::OK);
    let entries = root.join("offload/agent-e2e/offload-session-e2e.jsonl");
    assert!(
        entries.is_file(),
        "offload route must persist through the real engine"
    );
    let persisted = std::fs::read_to_string(entries).unwrap();
    assert!(persisted.contains("call-1"));
    assert!(root.join("offload/agent-e2e/state.json").is_file());
    assert!(
        root.join("offload/agent-e2e/refs")
            .read_dir()
            .unwrap()
            .next()
            .is_some()
    );
    let _ = std::fs::remove_dir_all(root);
}

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn production_builder_capture_search_recall_flush_and_disabled_offload() {
    let root = std::env::temp_dir().join(format!("aeon-memory-runtime-e2e-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&root);
    let mut config = GatewayConfig::default();
    config.data.base_dir = root.to_string_lossy().into_owned();
    config.llm.base_url = llm_server().await;
    config.llm.api_key = "test-key".into();
    config.llm.model = "test-model".into();
    config.memory.embedding.enabled = false;
    config.memory.recall.strategy = RecallStrategy::Keyword;
    config.memory.pipeline.enable_warmup = false;
    config.memory.pipeline.every_n_conversations = 100;
    let service = build_core(&config).await.unwrap();

    let captured = service
        .capture(CaptureRequest {
            user_content: "remember the cobalt bicycle".into(),
            assistant_content: "I will remember it".into(),
            session_key: "session-e2e".into(),
            session_id: Some("sid-e2e".into()),
            user_id: None,
            messages: None,
        })
        .await
        .unwrap();
    assert_eq!(captured.l0_recorded, 2);
    assert!(captured.scheduler_notified);
    assert!(root.join("vectors.db").is_file());
    assert!(
        root.join("conversations")
            .read_dir()
            .unwrap()
            .next()
            .is_some()
    );

    let search = service
        .search_conversations(ConversationSearchRequest {
            query: "cobalt bicycle".into(),
            limit: Some(5),
            session_key: Some("session-e2e".into()),
        })
        .await
        .unwrap();
    assert!(search.total >= 1, "L0 FTS must expose captured traffic");
    let recall = service
        .recall(RecallRequest {
            query: "cobalt bicycle".into(),
            session_key: "session-e2e".into(),
            user_id: None,
        })
        .await
        .unwrap();
    assert!(
        recall.strategy.is_none(),
        "an empty recall must not expose a Rust-only strategy field"
    );
    assert!(
        service
            .end_session(SessionEndRequest {
                session_key: "session-e2e".into(),
                user_id: None
            })
            .await
            .unwrap()
            .flushed
    );
    let checkpoint = read_checkpoint(&root.to_string_lossy()).unwrap();
    assert!(
        checkpoint.runner_states["session-e2e"].last_l1_cursor > 0,
        "the empty pipeline notification must reload persisted L0 and advance L1"
    );

    let error = service
        .before_prompt(BeforePromptRequest {
            agent_id: "a".into(),
            session_id: "s".into(),
            system_prompt: "sys".into(),
            user_prompt: "user".into(),
            messages: vec![],
            context_window: 1000,
        })
        .await
        .unwrap_err();
    assert!(error.to_string().contains("offload is disabled"));
    let _ = std::fs::remove_dir_all(root);
}

#[tokio::test]
async fn production_builder_rejects_missing_llm() {
    let mut config = GatewayConfig::default();
    config.llm.api_key.clear();
    let error = build_core(&config)
        .await
        .err()
        .expect("missing LLM must fail");
    assert!(error.to_string().contains("external LLM"));
}

#[tokio::test]
async fn original_typescript_embedding_metadata_starts_without_false_provider_drift() {
    let root = std::env::temp_dir().join(format!(
        "aeon-memory-ts-db-provider-compat-{}",
        std::process::id()
    ));
    let _ = std::fs::remove_dir_all(&root);
    std::fs::create_dir_all(&root).unwrap();
    let db_path = root.join("vectors.db");
    {
        let connection = rusqlite::Connection::open(&db_path).unwrap();
        connection
            .execute_batch(
                "CREATE TABLE embedding_meta (key TEXT PRIMARY KEY, value TEXT NOT NULL);",
            )
            .unwrap();
        connection
            .execute(
                "INSERT INTO embedding_meta (key, value) VALUES ('embedding_provider_info', ?1)",
                [r#"{"provider":"openai","model":"fixture-embedding","dimensions":3}"#],
            )
            .unwrap();
    }

    let mut config = GatewayConfig::default();
    config.data.base_dir = root.to_string_lossy().into_owned();
    config.llm.base_url = llm_server().await;
    config.llm.api_key = "test-key".into();
    config.llm.model = "test-model".into();
    config.memory.embedding.enabled = true;
    config.memory.embedding.provider = "openai".into();
    config.memory.embedding.base_url = "http://127.0.0.1:9/v1".into();
    config.memory.embedding.api_key = "embedding-key".into();
    config.memory.embedding.model = "fixture-embedding".into();
    config.memory.embedding.dimensions = 3;
    config.memory.extraction.enabled = false;
    let service = build_core(&config).await.unwrap();
    let health = service.health().await.unwrap();
    assert!(health.stores.embedding_service);

    let connection = rusqlite::Connection::open(&db_path).unwrap();
    let metadata: String = connection
        .query_row(
            "SELECT value FROM embedding_meta WHERE key = 'embedding_provider_info'",
            [],
            |row| row.get(0),
        )
        .unwrap();
    let metadata: serde_json::Value = serde_json::from_str(&metadata).unwrap();
    assert_eq!(metadata["provider"], "openai");
    assert_eq!(metadata["model"], "fixture-embedding");
    drop(connection);
    service.shutdown().await.unwrap();
    drop(service);
    let _ = std::fs::remove_dir_all(root);
}

#[tokio::test]
async fn health_reports_usable_sqlite_store_without_embedding_service() {
    let root =
        std::env::temp_dir().join(format!("aeon-memory-health-store-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&root);
    let mut config = GatewayConfig::default();
    config.data.base_dir = root.to_string_lossy().into_owned();
    config.llm.base_url = llm_server().await;
    config.llm.api_key = "test-key".into();
    config.llm.model = "test-model".into();
    config.memory.embedding.enabled = false;
    config.memory.extraction.enabled = false;
    let service = build_core(&config).await.unwrap();
    let health = service.health().await.unwrap();
    assert!(health.stores.vector_store);
    assert!(!health.stores.embedding_service);
    service.shutdown().await.unwrap();
    drop(service);
    let _ = std::fs::remove_dir_all(root);
}

#[tokio::test]
async fn corrupt_sqlite_degrades_to_no_store_without_blocking_service_startup() {
    let root = std::env::temp_dir().join(format!(
        "aeon-memory-health-corrupt-store-{}",
        std::process::id()
    ));
    let _ = std::fs::remove_dir_all(&root);
    std::fs::create_dir_all(&root).unwrap();
    std::fs::write(root.join("vectors.db"), b"not a sqlite database").unwrap();
    let mut config = GatewayConfig::default();
    config.data.base_dir = root.to_string_lossy().into_owned();
    let (llm_url, events) = task_aware_llm_server().await;
    config.llm.base_url = llm_url;
    config.llm.api_key = "test-key".into();
    config.llm.model = "test-model".into();
    config.memory.embedding.enabled = false;
    config.memory.extraction.enabled = true;
    config.memory.pipeline.enable_warmup = false;
    config.memory.pipeline.every_n_conversations = 100;

    let service = build_core(&config).await.unwrap();
    let health = service.health().await.unwrap();
    assert!(!health.stores.vector_store);
    assert!(!health.stores.embedding_service);
    service
        .capture(CaptureRequest {
            user_content: "capture survives unavailable sqlite".into(),
            assistant_content: "acknowledged".into(),
            session_key: "degraded-session".into(),
            session_id: Some("degraded-session-id".into()),
            user_id: None,
            messages: None,
        })
        .await
        .unwrap();
    assert!(root.join("conversations").exists());
    service
        .end_session(SessionEndRequest {
            session_key: "degraded-session".into(),
            user_id: None,
        })
        .await
        .unwrap();
    assert!(
        root.join("records").read_dir().unwrap().next().is_some(),
        "degraded runtime must extract L1 from canonical JSONL"
    );
    let seed = service
        .seed(SeedRequest {
            data: serde_json::json!({
                "sessions": [{
                    "sessionKey": "degraded-seed",
                    "sessionId": "degraded-seed-id",
                    "conversations": [[
                        {"role":"user","content":"seed survives parent sqlite degradation","timestamp":1783900000000_i64},
                        {"role":"assistant","content":"acknowledged","timestamp":1783900000001_i64}
                    ]]
                }]
            }),
            session_key: None,
            strict_round_role: None,
            auto_fill_timestamps: Some(true),
            config_override: None,
        })
        .await
        .unwrap();
    assert_eq!(seed.rounds_processed, 1);
    assert!(
        std::path::Path::new(&seed.output_dir)
            .join("conversations")
            .exists()
    );
    service.shutdown().await.unwrap();
    let events = events.lock().unwrap().clone();
    assert!(events.contains(&"l1".to_owned()));
    assert!(events.contains(&"l2".to_owned()));
    drop(service);
    let _ = std::fs::remove_dir_all(root);
}

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn real_cli_capture_drains_l1_and_l2_before_process_exit() {
    let root = std::env::temp_dir().join(format!(
        "aeon-memory-real-cli-shutdown-{}",
        std::process::id()
    ));
    let _ = std::fs::remove_dir_all(&root);
    std::fs::create_dir_all(&root).unwrap();
    let (llm_url, events) = task_aware_llm_server().await;
    let config_path = root.join("config.yaml");
    std::fs::write(
        &config_path,
        format!(
            "data:\n  baseDir: {:?}\nllm:\n  baseUrl: {:?}\n  apiKey: test-key\n  model: test-model\nmemory:\n  embedding:\n    enabled: false\n  pipeline:\n    enableWarmup: true\n    l2DelayAfterL1Seconds: 10\n",
            root.to_string_lossy(),
            llm_url,
        ),
    )
    .unwrap();
    let output = tokio::task::spawn_blocking(move || {
        std::process::Command::new(env!("CARGO_BIN_EXE_aeon-memory"))
            .args([
                "--config",
                config_path.to_str().unwrap(),
                "capture",
                "--user",
                "remember degraded cli lifecycle",
                "--assistant",
                "acknowledged",
                "--session-key",
                "cli-session",
                "--session-id",
                "cli-session-id",
            ])
            .output()
            .unwrap()
    })
    .await
    .unwrap();
    assert!(
        output.status.success(),
        "stdout={} stderr={}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    assert!(root.join("records").read_dir().unwrap().next().is_some());
    let events = events.lock().unwrap().clone();
    assert!(events.contains(&"l1".to_owned()));
    assert!(events.contains(&"l2".to_owned()));
    let _ = std::fs::remove_dir_all(root);
}

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn runtime_applies_distinct_recall_and_capture_embedding_timeouts() {
    let root = std::env::temp_dir().join(format!(
        "aeon-memory-runtime-embedding-timeouts-{}",
        std::process::id()
    ));
    let _ = std::fs::remove_dir_all(&root);
    let mut config = GatewayConfig::default();
    config.data.base_dir = root.to_string_lossy().into_owned();
    config.llm.base_url = llm_server().await;
    config.llm.api_key = "test-key".into();
    config.llm.model = "test-model".into();
    config.memory.embedding.enabled = true;
    config.memory.embedding.provider = "openai".into();
    config.memory.embedding.base_url = delayed_embedding_server(300).await;
    config.memory.embedding.api_key = "embedding-key".into();
    config.memory.embedding.model = "fixture-embedding".into();
    config.memory.embedding.dimensions = 3;
    config.memory.embedding.timeout_ms = 2_000;
    config.memory.embedding.recall_timeout_ms = Some(35);
    config.memory.embedding.capture_timeout_ms = Some(55);
    config.memory.extraction.enabled = false;
    let service = build_core(&config).await.unwrap();

    let recall_started = std::time::Instant::now();
    let recalled = service
        .recall(RecallRequest {
            query: "a sufficiently long vector query".into(),
            session_key: "timeout-session".into(),
            user_id: None,
        })
        .await
        .unwrap();
    assert!(recall_started.elapsed() < std::time::Duration::from_secs(6));
    assert_eq!(recalled.context, "");
    assert_eq!(recalled.memory_count, 0);
    assert!(recalled.strategy.is_none());

    service
        .capture(CaptureRequest {
            user_content: "capture vector timeout".into(),
            assistant_content: "acknowledged".into(),
            session_key: "timeout-session".into(),
            session_id: Some("timeout-session-id".into()),
            user_id: None,
            messages: None,
        })
        .await
        .unwrap();
    let drain_started = std::time::Instant::now();
    service.shutdown().await.unwrap();
    assert!(drain_started.elapsed() < std::time::Duration::from_secs(6));
    drop(service);
    let _ = std::fs::remove_dir_all(root);
}

#[tokio::test]
async fn production_qclaw_matches_pinned_ts_factory_and_calls_base_url_directly() {
    let root = std::env::temp_dir().join(format!(
        "aeon-memory-runtime-qclaw-direct-{}",
        std::process::id()
    ));
    let _ = std::fs::remove_dir_all(&root);
    let (base_url, requests) = recording_embedding_server().await;
    let mut config = GatewayConfig::default();
    config.data.base_dir = root.to_string_lossy().into_owned();
    config.llm.base_url = llm_server().await;
    config.llm.api_key = "test-key".into();
    config.llm.model = "test-model".into();
    config.memory.embedding.enabled = true;
    config.memory.embedding.provider = "qclaw".into();
    config.memory.embedding.base_url = base_url;
    config.memory.embedding.proxy_url = Some("http://127.0.0.1:1/proxy".into());
    config.memory.embedding.api_key = "embedding-key".into();
    config.memory.embedding.model = "fixture-embedding".into();
    config.memory.embedding.dimensions = 3;
    config.memory.extraction.enabled = false;
    let service = build_core(&config).await.unwrap();

    service
        .recall(RecallRequest {
            query: "a sufficiently long qclaw query".into(),
            session_key: "qclaw-session".into(),
            user_id: None,
        })
        .await
        .unwrap();
    {
        let captured = requests.lock().unwrap();
        assert_eq!(captured.len(), 1);
        assert!(captured[0].starts_with("POST /embeddings HTTP/1.1"));
        assert!(!captured[0].to_ascii_lowercase().contains("remote-url:"));
    }
    service.shutdown().await.unwrap();
    drop(service);
    let _ = std::fs::remove_dir_all(root);
}

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn disabled_extraction_persists_l0_without_notifying_pipeline() {
    let oracle: serde_json::Value =
        serde_json::from_str(include_str!("fixtures/disabled_capture_oracle.json")).unwrap();
    let root = std::env::temp_dir().join(format!(
        "aeon-memory-runtime-extraction-disabled-{}",
        std::process::id()
    ));
    let _ = std::fs::remove_dir_all(&root);
    let mut config = GatewayConfig::default();
    config.data.base_dir = root.to_string_lossy().into_owned();
    config.llm.base_url = llm_server().await;
    config.llm.api_key = "test-key".into();
    config.llm.model = "test-model".into();
    config.memory.embedding.enabled = false;
    config.memory.extraction.enabled = false;
    let service = build_core(&config).await.unwrap();
    let base = chrono::Utc::now().timestamp_millis() + 10_000;
    let first_messages = vec![
        serde_json::json!({"role":"user","content":"user message one","timestamp":base + 1}),
        serde_json::json!({"role":"assistant","content":"assistant answer one","timestamp":base + 2}),
    ];

    let captured = service
        .capture(CaptureRequest {
            user_content: "user message one".into(),
            assistant_content: "assistant answer one".into(),
            session_key: "disabled-extraction".into(),
            session_id: Some("disabled-extraction-id".into()),
            user_id: None,
            messages: Some(first_messages.clone()),
        })
        .await
        .unwrap();
    assert_eq!(
        captured.l0_recorded,
        oracle["body"]["l0_recorded"].as_u64().unwrap() as usize
    );
    assert_eq!(
        captured.scheduler_notified,
        oracle["body"]["scheduler_notified"].as_bool().unwrap()
    );
    let mut full_history = first_messages;
    full_history.extend([
        serde_json::json!({"role":"user","content":"user message two","timestamp":base + 3}),
        serde_json::json!({"role":"assistant","content":"assistant answer two","timestamp":base + 4}),
    ]);
    let second = service
        .capture(CaptureRequest {
            user_content: "user message two".into(),
            assistant_content: "assistant answer two".into(),
            session_key: "disabled-extraction".into(),
            session_id: Some("disabled-extraction-id".into()),
            user_id: None,
            messages: Some(full_history),
        })
        .await
        .unwrap();
    assert_eq!(
        second.l0_recorded,
        oracle["secondBody"]["l0_recorded"].as_u64().unwrap() as usize
    );
    assert_eq!(
        second.scheduler_notified,
        oracle["secondBody"]["scheduler_notified"]
            .as_bool()
            .unwrap()
    );
    service
        .end_session(SessionEndRequest {
            session_key: "disabled-extraction".into(),
            user_id: None,
        })
        .await
        .unwrap();

    let checkpoint_path = root.join(".metadata/recall_checkpoint.json");
    assert!(
        checkpoint_path.exists(),
        "L0 capture must retain the TS atomic cursor checkpoint"
    );
    let checkpoint = read_checkpoint(&root.to_string_lossy()).unwrap();
    assert_eq!(
        checkpoint.total_processed,
        oracle["totalProcessed"].as_u64().unwrap()
    );
    assert_eq!(
        checkpoint.l0_conversations_count,
        oracle["l0ConversationsCount"].as_u64().unwrap()
    );
    assert_eq!(
        checkpoint.runner_states["disabled-extraction"].last_captured_timestamp > 0,
        oracle["runnerState"]["lastCapturedTimestampPositive"]
            .as_bool()
            .unwrap()
    );
    assert_eq!(
        checkpoint.runner_states["disabled-extraction"].last_l1_cursor,
        oracle["runnerState"]["lastL1Cursor"].as_i64().unwrap()
    );
    assert_eq!(
        checkpoint.pipeline_states.len(),
        oracle["pipelineStateCount"].as_u64().unwrap() as usize
    );
    let mut store =
        aeon_memory_store_sqlite::VectorStore::new(&root.join("vectors.db").to_string_lossy(), 0);
    store.init(None).unwrap();
    assert_eq!(
        store.count_l0().unwrap(),
        oracle["totalProcessed"].as_i64().unwrap()
    );
    assert_eq!(store.count_l1().unwrap(), 0);
    let _ = std::fs::remove_dir_all(root);
}

#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn mock_l1_shape_advances_warmup_and_drives_l2_l3_for_two_sessions() {
    let root = std::env::temp_dir().join(format!(
        "aeon-memory-runtime-mock-shape-{}",
        std::process::id()
    ));
    let _ = std::fs::remove_dir_all(&root);
    let (base_url, events) = task_aware_llm_server().await;
    let mut config = GatewayConfig::default();
    config.data.base_dir = root.to_string_lossy().into_owned();
    config.llm.base_url = base_url;
    config.llm.api_key = "test-key".into();
    config.llm.model = "mock".into();
    config.memory.embedding.enabled = false;
    config.memory.pipeline.enable_warmup = true;
    config.memory.pipeline.every_n_conversations = 5;
    config.memory.pipeline.l2_delay_after_l1_seconds = 0;
    config.memory.pipeline.l2_min_interval_seconds = 0;
    let service = build_core(&config).await.unwrap();

    for session in ["alpha", "beta"] {
        service
            .capture(CaptureRequest {
                user_content: format!("{session}：用户希望优化数据库查询性能"),
                assistant_content: "noted".into(),
                session_key: session.into(),
                session_id: Some(session.into()),
                user_id: None,
                messages: None,
            })
            .await
            .unwrap();
    }
    for session in ["alpha", "beta"] {
        service
            .end_session(SessionEndRequest {
                session_key: session.into(),
                user_id: None,
            })
            .await
            .unwrap();
    }
    tokio::time::sleep(std::time::Duration::from_millis(500)).await;

    let checkpoint = read_checkpoint(&root.to_string_lossy()).unwrap();
    for session in ["alpha", "beta"] {
        assert!(checkpoint.runner_states[session].last_l1_cursor > 0);
        assert_eq!(
            checkpoint.runner_states[session].last_scene_name,
            "Differential Test Scene"
        );
        assert_eq!(checkpoint.pipeline_states[session].conversation_count, 0);
        assert_eq!(checkpoint.pipeline_states[session].warmup_threshold, 2);
    }
    assert_eq!(checkpoint.total_memories_extracted, 2);
    assert_eq!(checkpoint.scenes_processed, 2);

    let mut persisted =
        aeon_memory_store_sqlite::VectorStore::new(&root.join("vectors.db").to_string_lossy(), 0);
    persisted.init(None).unwrap();
    let rows = persisted
        .query_l1_records(&L1QueryFilter::default())
        .unwrap();
    assert_eq!(rows.len(), 2);
    for row in rows {
        assert!(!row.timestamp_str.is_empty());
        assert_eq!(row.timestamp_start, row.timestamp_str);
        assert_eq!(row.timestamp_end, row.timestamp_str);
    }
    let events = events.lock().unwrap().clone();
    assert_eq!(events.iter().filter(|task| *task == "l1").count(), 2);
    assert_eq!(
        events.iter().filter(|task| *task == "dedup").count(),
        1,
        "embedding=none must still recall the first session's tokenized Chinese L1 record and invoke batch dedup for the second session"
    );
    assert_eq!(events.iter().filter(|task| *task == "l2").count(), 2);
    assert!(events.iter().any(|task| task == "l3"));
    assert!(root.join(".metadata/manifest.json").is_file());

    let records = std::fs::read_to_string(
        root.join("records")
            .read_dir()
            .unwrap()
            .next()
            .unwrap()
            .unwrap()
            .path(),
    )
    .unwrap();
    for line in records.lines() {
        let record: serde_json::Value = serde_json::from_str(line).unwrap();
        assert!(record["id"].as_str().unwrap().starts_with("m_"));
        assert!(record.get("scene_name").is_some());
        assert!(record.get("source_message_ids").is_some());
        assert_eq!(record["timestamps"].as_array().unwrap().len(), 1);
    }
    let _ = std::fs::remove_dir_all(root);
}
