//! Deterministic differential replay of the pinned TypeScript VectorStore's
//! embedding configuration lifecycle. The oracle is generated by executing
//! the real TS store; this test independently replays the same operations via
//! Rust's public IMemoryStore boundary and compares every observable exactly.

use aeon_memory_core::error::AeonMemoryCoreError;
use aeon_memory_core::types::{
    EmbeddingProviderInfo, IMemoryStore, L0Record, L1RecordRow, ReindexLayer,
};
use aeon_memory_store_sqlite::{VectorStore, connection::StoreConnection, schema};
use serde_json::{Value, json};
use std::path::PathBuf;
use std::time::{SystemTime, UNIX_EPOCH};

const BASELINE: &str = "4339e63650920871eb0e8888083a1779d114e3ae";

fn provider(provider: &str, model: &str) -> EmbeddingProviderInfo {
    EmbeddingProviderInfo {
        provider: provider.into(),
        model: model.into(),
    }
}

fn init_view(result: aeon_memory_core::types::StoreInitResult) -> Value {
    json!({
        "needsReindex": result.needs_reindex,
        "reason": result.reason,
    })
}

fn deterministic_vector(text: &str, dimensions: usize) -> Vec<f32> {
    let mut values = vec![0.0; dimensions];
    if text.ends_with("alpha") {
        values[0] = 1.0;
        values[1] = if text.starts_with("raw") { 0.25 } else { 0.0 };
    } else {
        values[0] = if text.starts_with("raw") { 0.25 } else { 0.0 };
        values[1] = 1.0;
    }
    values
}

fn stored_vectors(db_path: &str, table: &str) -> Value {
    assert!(matches!(table, "l1_vec" | "l0_vec"));
    let connection = StoreConnection::open_readonly(db_path).unwrap();
    let conn = connection.conn.lock().unwrap();
    assert!(schema::try_load_vec_extension(&conn));
    let sql = format!("SELECT record_id, vec_to_json(embedding) FROM {table} ORDER BY record_id");
    let mut statement = conn.prepare(&sql).unwrap();
    let rows = statement
        .query_map([], |row| {
            Ok((row.get::<_, String>(0)?, row.get::<_, String>(1)?))
        })
        .unwrap()
        .collect::<Result<Vec<_>, _>>()
        .unwrap();
    Value::Array(
        rows.into_iter()
            .map(|(id, encoded)| {
                let values: Vec<f64> = serde_json::from_str(&encoded).unwrap();
                json!({
                    "id": id,
                    "vector": values
                        .into_iter()
                        .map(|value| format!("{value:.6}"))
                        .collect::<Vec<_>>(),
                })
            })
            .collect(),
    )
}

fn inspect(store: &VectorStore, db_path: &str, dimensions: usize) -> Value {
    let query = deterministic_vector("memory alpha", dimensions);
    let l1 = store
        .search_l1_vector(&query, 10)
        .unwrap()
        .into_iter()
        .map(|row| row.record_id)
        .collect::<Vec<_>>();
    let l0 = store
        .search_l0_vector(&query, 10)
        .unwrap()
        .into_iter()
        .map(|row| row.record_id)
        .collect::<Vec<_>>();

    let connection = StoreConnection::open_readonly(db_path).unwrap();
    let conn = connection.conn.lock().unwrap();
    assert!(schema::try_load_vec_extension(&conn));
    let l1_count: i64 = conn
        .query_row("SELECT count(*) FROM l1_vec", [], |row| row.get(0))
        .unwrap();
    let l0_count: i64 = conn
        .query_row("SELECT count(*) FROM l0_vec", [], |row| row.get(0))
        .unwrap();
    drop(conn);
    drop(connection);

    json!({
        "vecCounts": { "l1": l1_count, "l0": l0_count },
        "search": { "l1": l1, "l0": l0 },
        "vectors": {
            "l1": stored_vectors(db_path, "l1_vec"),
            "l0": stored_vectors(db_path, "l0_vec"),
        },
    })
}

fn reindex_view(
    store: &mut VectorStore,
    db_path: &str,
    dimensions: usize,
    fail_text: Option<&str>,
) -> Value {
    let mut calls = Vec::new();
    let mut progress = Vec::new();
    let mut embed = |text: &str| {
        calls.push(text.to_string());
        if Some(text) == fail_text {
            Err(AeonMemoryCoreError::Store(
                "deterministic embedding failure".into(),
            ))
        } else {
            Ok(deterministic_vector(text, dimensions))
        }
    };
    let result = store
        .reindex_all(
            &mut embed,
            Some(&mut |done, total, layer| {
                progress.push(json!({
                    "done": done,
                    "total": total,
                    "layer": match layer { ReindexLayer::L1 => "L1", ReindexLayer::L0 => "L0" },
                }));
            }),
        )
        .unwrap();
    json!({
        "result": { "l1Count": result.l1_count, "l0Count": result.l0_count },
        "calls": calls,
        "progress": progress,
        "vecCounts": inspect(store, db_path, dimensions)["vecCounts"].clone(),
        "search": inspect(store, db_path, dimensions)["search"].clone(),
        "vectors": inspect(store, db_path, dimensions)["vectors"].clone(),
    })
}

fn insert_existing_records(store: &mut VectorStore) {
    for (id, content, priority, second) in [
        ("l1-alpha", "memory alpha", 80.0, 0),
        ("l1-beta", "memory beta", 70.0, 1),
    ] {
        assert!(
            store
                .upsert_l1(
                    &L1RecordRow {
                        record_id: id.into(),
                        content: content.into(),
                        r#type: "fact".into(),
                        priority,
                        scene_name: String::new(),
                        session_key: "session".into(),
                        session_id: "sid".into(),
                        timestamp_str: "2026-07-13".into(),
                        timestamp_start: String::new(),
                        timestamp_end: String::new(),
                        created_time: format!("2026-07-13T01:00:0{second}.000Z"),
                        updated_time: format!("2026-07-13T01:00:0{second}.000Z"),
                        metadata_json: "{}".into(),
                    },
                    None,
                )
                .unwrap()
        );
    }
    for (id, text, role, second, timestamp) in [
        ("l0-alpha", "raw alpha", "user", 2, 1_783_904_402_000_i64),
        ("l0-beta", "raw beta", "assistant", 3, 1_783_904_403_000_i64),
    ] {
        assert!(
            store
                .upsert_l0(
                    &L0Record {
                        id: id.into(),
                        session_key: "session".into(),
                        session_id: "sid".into(),
                        role: role.into(),
                        message_text: text.into(),
                        recorded_at: format!("2026-07-13T01:00:0{second}.000Z"),
                        timestamp,
                    },
                    None,
                )
                .unwrap()
        );
    }
}

#[test]
fn pinned_ts_and_rust_embedding_lifecycles_are_identical() {
    let oracle: Value =
        serde_json::from_str(include_str!("fixtures/embedding_reindex_oracle.json")).unwrap();
    assert_eq!(oracle["baseline"], BASELINE);

    // Keep this differential test independent of machine-wide dynamic-library
    // search paths and avoid repeatedly traversing PATH for each inspection
    // connection. The fixture is the same native sqlite-vec binary used by the
    // store package's compatibility tests.
    let prior_vec0 = std::env::var_os("AEON_MEMORY_VEC0_PATH");
    let vec0 = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join(if cfg!(target_os = "macos") {
            "vec0.dylib"
        } else if cfg!(target_os = "windows") {
            "vec0.dll"
        } else {
            "vec0.so"
        });
    assert!(vec0.exists(), "native sqlite-vec fixture is required");
    // SAFETY: this integration-test binary contains one test, so no other
    // thread in the process can observe the temporary override.
    unsafe { std::env::set_var("AEON_MEMORY_VEC0_PATH", &vec0) };

    let unique = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap()
        .as_nanos();
    let root = std::env::temp_dir().join(format!(
        "aeon-memory-embedding-differential-{}-{unique}",
        std::process::id()
    ));
    std::fs::create_dir_all(&root).unwrap();
    let db: PathBuf = root.join("vectors.db");
    let db_path = db.to_str().unwrap();

    let mut store = VectorStore::new(db_path, 0);
    assert_eq!(init_view(store.init(None).unwrap()), oracle["noneInit"]);
    insert_existing_records(&mut store);
    assert_eq!(
        json!({ "l1":store.count_l1().unwrap(), "l0":store.count_l0().unwrap() }),
        oracle["noneCounts"]
    );
    store.close();

    let mut store = VectorStore::new(db_path, 4);
    assert_eq!(
        init_view(
            store
                .init(Some(&provider("provider-a", "model-a")))
                .unwrap()
        ),
        oracle["enableInit"]
    );
    assert_eq!(
        reindex_view(&mut store, db_path, 4, Some("memory beta")),
        oracle["enableReindex"]
    );
    store.close();

    let mut store = VectorStore::new(db_path, 4);
    assert_eq!(
        init_view(
            store
                .init(Some(&provider("provider-a", "model-a")))
                .unwrap()
        ),
        oracle["sameConfigInit"]
    );
    assert_eq!(inspect(&store, db_path, 4), oracle["sameConfigState"]);
    store.close();

    let mut store = VectorStore::new(db_path, 4);
    assert_eq!(
        init_view(
            store
                .init(Some(&provider("provider-b", "model-a")))
                .unwrap()
        ),
        oracle["providerChangeInit"]
    );
    assert_eq!(
        reindex_view(&mut store, db_path, 4, None),
        oracle["providerChangeReindex"]
    );
    store.close();

    let mut store = VectorStore::new(db_path, 4);
    assert_eq!(
        init_view(
            store
                .init(Some(&provider("provider-b", "model-b")))
                .unwrap()
        ),
        oracle["modelChangeInit"]
    );
    assert_eq!(
        reindex_view(&mut store, db_path, 4, None),
        oracle["modelChangeReindex"]
    );
    store.close();

    let mut store = VectorStore::new(db_path, 6);
    assert_eq!(
        init_view(
            store
                .init(Some(&provider("provider-b", "model-b")))
                .unwrap()
        ),
        oracle["dimensionsChangeInit"]
    );
    assert_eq!(
        reindex_view(&mut store, db_path, 6, None),
        oracle["dimensionsChangeReindex"]
    );
    store.close();

    std::fs::remove_dir_all(root).unwrap();
    match prior_vec0 {
        Some(value) => unsafe { std::env::set_var("AEON_MEMORY_VEC0_PATH", value) },
        None => unsafe { std::env::remove_var("AEON_MEMORY_VEC0_PATH") },
    }
}
