#!/usr/bin/env node
import http from "node:http";

const port = Number(process.argv[2] ?? 18419);
let sequence = 0;
let control = { delayMs: 0, failNext: 0, failStatus: 503 };
const failedByAuthorization = new Map();
const events = [];
const now = () => Number(process.hrtime.bigint() / 1000000n);

function json(res, status, value) {
  res.writeHead(status, { "content-type": "application/json" });
  res.end(JSON.stringify(value));
}
function taskOf(path, body) {
  if (path.includes("embeddings")) return "embedding";
  const text = JSON.stringify(body.messages ?? []);
  // Both prompts mention persona.md and scene_blocks in their sandbox rules;
  // classify on their unique role headers to keep L2/L3 causality observable.
  if (/Persona Architect - Incremental Evolution Protocol|Persona Generation Prompt/.test(text)) return "l3";
  if (/Memory Consolidation Architect|Scene Extraction Prompt/.test(text)) return "l2";
  if (/conflict detection|dedup|重复记忆|冲突检测/i.test(text)) return "dedup";
  if (/source_message_ids|情境切分与记忆提取|Memory Extraction/.test(text)) return "l1";
  return "chat";
}
function completion(task, body) {
  const prompt = JSON.stringify(body.messages ?? []);
  const ids = [...new Set(prompt.match(/l0_[A-Za-z0-9_.:-]+/g) ?? [])].slice(0, 32);
  let content = "[]";
  if (task === "l1") {
    content = JSON.stringify([{
      scene_name: "Differential Test Scene", message_ids: ids,
      memories: ids.length ? [{
        content: "The user is running the differential parity test",
        type: "episodic", priority: 80, source_message_ids: ids, metadata: {}
      }] : []
    }]);
  } else if (task === "l2") {
    content = "PERSONA_UPDATE_REQUEST: deterministic differential change";
  } else if (task === "l3") {
    content = "# Test Persona\n\nGenerated by deterministic mock.";
  }
  return {
    id: `mock-${sequence}`, object: "chat.completion", created: 1,
    model: body.model ?? "mock", choices: [{ index: 0,
      message: { role: "assistant", content }, finish_reason: "stop" }],
    usage: { prompt_tokens: 10, completion_tokens: 10, total_tokens: 20 }
  };
}

http.createServer((req, res) => {
  let raw = "";
  req.on("data", chunk => raw += chunk);
  req.on("end", () => {
    if (req.url === "/__log" && req.method === "GET") return json(res, 200, events);
    if (req.url === "/__reset" && req.method === "POST") {
      events.length = 0; sequence = 0; failedByAuthorization.clear();
      control = { delayMs: 0, failNext: 0, failStatus: 503 };
      return json(res, 200, { ok: true });
    }
    if (req.url === "/__control" && req.method === "POST") {
      control = { ...control, ...JSON.parse(raw || "{}") };
      return json(res, 200, control);
    }
    let body;
    try { body = JSON.parse(raw || "{}"); }
    catch { return json(res, 400, { error: "invalid mock request" }); }
    const task = taskOf(req.url ?? "", body);
    const event = {
      seq: ++sequence, task, path: req.url, authorization: req.headers.authorization ?? null,
      started_ms: now(), completed_ms: null, status: null,
      body
    };
    events.push(event);
    const delay = Number(control.delayMs || 0);
    const authorization = req.headers.authorization ?? "<none>";
    const alreadyFailed = failedByAuthorization.get(authorization) ?? 0;
    const failPerKey = Number(control.failNextPerKey || 0);
    const fail = failPerKey > alreadyFailed || control.failNext > 0;
    if (failPerKey > alreadyFailed) failedByAuthorization.set(authorization, alreadyFailed + 1);
    else if (fail) control.failNext--;
    setTimeout(() => {
      event.completed_ms = now();
      if (fail) {
        event.status = Number(control.failStatus || 503);
        return json(res, event.status, { error: { message: "planned mock failure" } });
      }
      event.status = 200;
      if (task === "embedding") {
        const count = Array.isArray(body.input) ? body.input.length : 1;
        return json(res, 200, { object: "list", model: body.model ?? "mock-embedding",
          data: Array.from({length: count}, (_, index) => ({object:"embedding", index, embedding:[1,0,0,0]})),
          usage: {prompt_tokens: count, total_tokens: count} });
      }
      json(res, 200, completion(task, body));
    }, delay);
  });
}).listen(port, "127.0.0.1", () => process.stdout.write(`mock-openai:${port}\n`));
