//! Differential and deterministic property corpus generated by executing the
//! immutable TypeScript implementation. Regenerate with
//! `AEON_MEMORY_TS_ORACLE_ROOT=... AEON_MEMORY_TSX_CLI=... node tests/fixtures/gen-ts-config-search-oracle.mjs`.
use serde::Deserialize;
use serde_json::{Value, json};

fn oracle() -> Oracle {
    serde_json::from_str(include_str!("fixtures/config_search_oracle.json")).unwrap()
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Oracle {
    config_cases: Vec<ConfigCase>,
    rrf_cases: Vec<RrfCase>,
    bm25_cases: Vec<Bm25Case>,
    fts_cases: Vec<FtsCase>,
}

#[derive(Deserialize)]
struct ConfigCase {
    input: Value,
    expected: Value,
}

#[derive(Clone, Deserialize)]
struct RrfItem {
    id: String,
    payload: usize,
}

#[derive(Deserialize)]
struct RrfCase {
    lists: Vec<Vec<RrfItem>>,
    k: f64,
    expected: Vec<RrfExpected>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct RrfExpected {
    id: String,
    payload: usize,
    rrf_score: f64,
}

#[derive(Deserialize)]
struct Bm25Case {
    rank: Value,
    expected: f64,
}

#[derive(Deserialize)]
struct FtsCase {
    input: String,
    query: Option<String>,
    indexed: String,
}

fn config_projection(config: &aeon_memory_core::config::AeonMemoryConfig) -> Value {
    let cleanup = if let Some(days) = config.memory_cleanup.retention_days {
        json!({"retentionDays": days, "enabled": config.memory_cleanup.enabled, "cleanTime": config.memory_cleanup.clean_time})
    } else {
        json!({"enabled": config.memory_cleanup.enabled, "cleanTime": config.memory_cleanup.clean_time})
    };
    json!({
        "timezone": config.timezone,
        "capture": {
            "enabled": config.capture.enabled,
            "excludeAgents": config.capture.exclude_agents,
            "l0l1RetentionDays": config.capture.l0l1_retention_days,
            "allowAggressiveCleanup": config.capture.allow_aggressive_cleanup,
        },
        "recall": config.recall,
        "embedding": {
            "enabled": config.embedding.enabled,
            "provider": config.embedding.provider,
            "baseUrl": config.embedding.base_url,
            "model": config.embedding.model,
            "dimensions": config.embedding.dimensions,
            "configError": config.embedding.config_error,
        },
        "storeBackend": config.store_backend,
        "memoryCleanup": cleanup,
        "offload": {
            "enabled": config.offload.enabled,
            "mode": config.offload.mode,
            "backendTimeoutMs": config.offload.backend_timeout_ms,
            "offloadRetentionDays": config.offload.offload_retention_days,
        }
    })
}

#[test]
fn config_normalization_matches_typescript_oracle() {
    for case in oracle().config_cases {
        let actual =
            aeon_memory_core::config::AeonMemoryConfig::from_json_value(case.input.clone())
                .unwrap_or_else(|error| {
                    panic!(
                        "TypeScript accepted {} but Rust rejected it: {error}",
                        case.input
                    )
                });
        assert_eq!(
            config_projection(&actual),
            case.expected,
            "input {}",
            case.input
        );
    }
}

#[test]
fn rrf_deterministic_property_corpus_matches_typescript_order_scores_and_payload() {
    for (index, case) in oracle().rrf_cases.into_iter().enumerate() {
        let actual = aeon_memory_core::search::rrf_merge(&case.lists, |item| &item.id, case.k);
        assert_eq!(actual.len(), case.expected.len(), "case {index}");
        for ((item, score), expected) in actual.iter().zip(case.expected) {
            assert_eq!(
                (&item.id, item.payload),
                (&expected.id, expected.payload),
                "case {index}"
            );
            assert!(
                (score - expected.rrf_score).abs() <= 1e-12,
                "case {index}: {score} != {}",
                expected.rrf_score
            );
        }
    }
}

#[test]
fn bm25_dense_numeric_corpus_matches_typescript() {
    for case in oracle().bm25_cases {
        let rank = case
            .rank
            .as_f64()
            .unwrap_or_else(|| match case.rank.as_str().unwrap() {
                "Infinity" => f64::INFINITY,
                "-Infinity" => f64::NEG_INFINITY,
                "NaN" => f64::NAN,
                other => panic!("unexpected rank {other}"),
            });
        let actual = aeon_memory_core::search::bm25_rank_to_score(rank);
        assert!(
            (actual - case.expected).abs() <= 1e-12,
            "rank {rank}: {actual} != {}",
            case.expected
        );
    }
}

#[test]
fn fts_query_and_index_tokenization_match_typescript_bytes() {
    for case in oracle().fts_cases {
        assert_eq!(
            aeon_memory_core::fts_query::build_fts_query(&case.input),
            case.query,
            "query input {:?}",
            case.input
        );
        assert_eq!(
            aeon_memory_core::fts_query::tokenize_for_fts(&case.input),
            case.indexed,
            "index input {:?}",
            case.input
        );
    }
}
