//! Byte- and field-exact compatibility checks against fixtures generated by
//! executing the TypeScript implementation. No fixture is optional.
use serde::Deserialize;
use std::path::PathBuf;

fn fixture_path(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures")
        .join(name)
}
fn fixture(name: &str) -> String {
    std::fs::read_to_string(fixture_path(name))
        .unwrap_or_else(|error| panic!("required TypeScript golden {name}: {error}"))
}

#[test]
fn stable_prompts_are_byte_exact() {
    assert_eq!(
        fixture("prompt_l1_extraction.txt").as_bytes(),
        aeon_memory_core::prompt::l1_extraction::EXTRACT_MEMORIES_SYSTEM_PROMPT.as_bytes()
    );
    assert_eq!(
        fixture("prompt_l1_dedup.txt").as_bytes(),
        aeon_memory_core::prompt::l1_dedup::L1_DEDUP_SYSTEM_PROMPT.as_bytes()
    );
    assert_eq!(
        fixture("prompt_persona_system.txt").as_bytes(),
        aeon_memory_core::persona::PERSONA_SYSTEM_PROMPT.as_bytes()
    );
    let (scene, _) = aeon_memory_core::scene::build_scene_extraction_prompt("", "", None, &[], 15);
    assert_eq!(
        fixture("prompt_scene_system_15.txt").as_bytes(),
        scene.as_bytes()
    );
}

#[test]
fn dynamic_extraction_prompt_is_byte_exact() {
    use aeon_memory_core::record::l0_recorder::ConversationMessage;
    let prompt = aeon_memory_core::prompt::l1_extraction::format_extraction_prompt(
        &[ConversationMessage {
            id: "n1".into(),
            role: "user".into(),
            content: "明天去杭州".into(),
            timestamp: 1_783_900_800_000,
        }],
        &[ConversationMessage {
            id: "b1".into(),
            role: "assistant".into(),
            content: "背景".into(),
            timestamp: 1_783_814_400_000,
        }],
        "旅行",
        "All timestamps below are in UTC (UTC+00:00). When reasoning about \"yesterday\", \"last week\", or time differences, use this timezone.",
    );
    assert_eq!(
        fixture("prompt_l1_extraction_dynamic.txt").as_bytes(),
        prompt.as_bytes()
    );
}

#[test]
fn dynamic_persona_prompt_is_byte_exact() {
    use aeon_memory_core::persona::{PersonaMode, PersonaPromptParams, build_persona_prompt};
    let prompt = build_persona_prompt(&PersonaPromptParams {
        mode: PersonaMode::Incremental,
        current_time: "2026-07-13 12:00:00",
        total_processed: 12,
        scene_count: 2,
        changed_scene_count: 1,
        changed_scenes_content: "changed",
        existing_persona: Some("old"),
        trigger_info: Some("reason"),
    });
    assert_eq!(
        fixture("prompt_persona_dynamic.txt").as_bytes(),
        prompt.user_prompt.as_bytes()
    );
}

#[derive(Deserialize)]
struct RrfFixture {
    lists: Vec<Vec<RrfItem>>,
    k: f64,
    expected: Vec<RrfExpected>,
}
#[derive(Clone, Deserialize)]
struct RrfItem {
    id: String,
}
#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct RrfExpected {
    id: String,
    rrf_score: f64,
}

#[test]
fn rrf_full_order_and_scores_match_ts() {
    let expected: RrfFixture =
        serde_json::from_str(&fixture("rrf_merge.json")).expect("rrf fixture JSON");
    let actual =
        aeon_memory_core::search::rrf_merge(&expected.lists, |item| item.id.as_str(), expected.k);
    assert_eq!(actual.len(), expected.expected.len());
    for ((item, score), wanted) in actual.iter().zip(&expected.expected) {
        assert_eq!(item.id, wanted.id);
        assert!(
            (score - wanted.rrf_score).abs() <= 1e-12,
            "{}: {score} != {}",
            item.id,
            wanted.rrf_score
        );
    }
}

#[derive(Deserialize)]
struct Bm25Fixture {
    cases: Vec<Bm25Case>,
}
#[derive(Deserialize)]
struct Bm25Case {
    rank: serde_json::Value,
    expected: f64,
}

#[test]
fn bm25_all_ts_cases_match_to_one_e_minus_twelve() {
    let expected: Bm25Fixture =
        serde_json::from_str(&fixture("bm25_rank.json")).expect("bm25 fixture JSON");
    for case in expected.cases {
        let rank = case.rank.as_f64().unwrap_or_else(|| {
            match case.rank.as_str().expect("rank number/string") {
                "Infinity" => f64::INFINITY,
                "-Infinity" => f64::NEG_INFINITY,
                "NaN" => f64::NAN,
                other => panic!("unexpected rank {other}"),
            }
        });
        let actual = aeon_memory_core::search::bm25_rank_to_score(rank);
        assert!(
            (actual - case.expected).abs() <= 1e-12,
            "rank {rank}: {actual} != {}",
            case.expected
        );
    }
}

#[derive(Deserialize)]
struct FtsFixture {
    cases: Vec<FtsCase>,
}
#[derive(Deserialize)]
struct FtsCase {
    input: String,
    expected: Option<String>,
}

#[test]
fn fts_queries_match_ts_exactly() {
    let expected: FtsFixture =
        serde_json::from_str(&fixture("fts_query.json")).expect("fts fixture JSON");
    for case in expected.cases {
        assert_eq!(
            aeon_memory_core::fts_query::build_fts_query(&case.input),
            case.expected,
            "input {:?}",
            case.input
        );
    }
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct JsonlFixture {
    input: JsonlInput,
    expected_value: serde_json::Value,
    expected_bytes: String,
}
#[derive(Deserialize)]
struct JsonlInput {
    id: String,
    content: String,
    r#type: String,
    priority: f64,
    scene_name: String,
    source_message_ids: Vec<String>,
    metadata: serde_json::Value,
    timestamps: Vec<String>,
    created_at: String,
    updated_at: String,
    session_key: String,
    session_id: String,
}

#[test]
fn l1_jsonl_value_and_bytes_match_ts() {
    let wanted: JsonlFixture =
        serde_json::from_str(&fixture("l1_jsonl_record.json")).expect("jsonl fixture JSON");
    let input = wanted.input;
    let record = aeon_memory_core::record::l1_writer::MemoryRecord {
        id: input.id,
        content: input.content,
        r#type: input.r#type,
        priority: input.priority,
        scene_name: input.scene_name,
        source_message_ids: input.source_message_ids,
        metadata: input.metadata,
        timestamps: input.timestamps,
        created_at: input.created_at,
        updated_at: input.updated_at,
        session_key: input.session_key,
        session_id: input.session_id,
    };
    let value = serde_json::to_value(&record).expect("serialize record value");
    assert_eq!(value, wanted.expected_value);
    let bytes = format!(
        "{}\n",
        serde_json::to_string(&record).expect("serialize JSONL record")
    );
    assert_eq!(bytes.as_bytes(), wanted.expected_bytes.as_bytes());
}
