//! Representative branch/state-machine replay against the fixture generated by
//! executing the pinned TypeScript `MemoryPipelineManager`.
use aeon_memory_core::pipeline::{
    checkpoint::PipelineSessionState,
    manager::{CapturedMessage, Clock, L2Result, PipelineConfig, PipelineManager, PipelineRunner},
};
use serde_json::{Value, json};
use std::{
    collections::HashMap,
    sync::{
        Arc, Mutex,
        atomic::{AtomicI64, AtomicUsize, Ordering},
    },
};

fn oracle() -> Value {
    serde_json::from_str(include_str!("fixtures/pipeline_branches.json")).unwrap()
}
struct TestClock(Arc<AtomicI64>);
impl Clock for TestClock {
    fn now_ms(&self) -> i64 {
        self.0.load(Ordering::SeqCst)
    }
}
#[derive(Clone, Copy)]
enum Mode {
    Retry,
    Exhaust,
    Recovery,
    Interleave,
}
struct Runner {
    mode: Mode,
    events: Arc<Mutex<Vec<Value>>>,
    attempts: Arc<AtomicUsize>,
}
impl PipelineRunner for Runner {
    fn run_l1(&mut self, s: &str, m: &[CapturedMessage]) -> Result<(), String> {
        let n = self.attempts.fetch_add(1, Ordering::SeqCst) + 1;
        match self.mode{Mode::Retry=>{self.events.lock().unwrap().push(json!({"kind":"l1","attempt":n,"count":m.len()}));if n<3{return Err("planned".into())}},Mode::Exhaust=>return Err("always".into()),Mode::Interleave=>self.events.lock().unwrap().push(json!({"kind":"l1","session":s,"contents":m.iter().map(|x|x.content.clone()).collect::<Vec<_>>()})),Mode::Recovery=>{}}
        Ok(())
    }
    fn run_l2(&mut self, s: &str, c: Option<&str>) -> Result<L2Result, String> {
        match self.mode {
            Mode::Retry => self.events.lock().unwrap().push(json!({"kind":"l2"})),
            Mode::Exhaust => {}
            Mode::Recovery => self
                .events
                .lock()
                .unwrap()
                .push(json!({"kind":"l2","session":s,"cursor":c})),
            Mode::Interleave => self
                .events
                .lock()
                .unwrap()
                .push(json!({"kind":"l2","session":s})),
        };
        Ok(L2Result {
            latest_cursor: matches!(self.mode, Mode::Recovery)
                .then(|| "2026-02-01T00:00:00Z".into()),
            skipped: !matches!(self.mode, Mode::Recovery),
        })
    }
    fn run_l3(&mut self) -> Result<(), String> {
        self.events.lock().unwrap().push(json!({"kind":"l3"}));
        Ok(())
    }
}

#[test]
fn retry_limit_preserves_failed_work_after_initial_plus_five_retries() {
    let e = Arc::new(Mutex::new(vec![]));
    let n = Arc::new(AtomicUsize::new(0));
    let c = Arc::new(AtomicI64::new(1000));
    let mut m = manager(Mode::Exhaust, config(1, 10, 10), c.clone(), e, n.clone());
    m.notify_conversation("fail", msg("x"));
    for _ in 0..6 {
        c.fetch_add(30_000, Ordering::SeqCst);
        m.run_due();
    }
    let expected = &oracle()["retryExhausted"];
    assert_eq!(n.load(Ordering::SeqCst), expected["attempts"]);
    assert_eq!(m.buffered_message_count("fail"), expected["buffered"]);
    assert_eq!(
        m.session_state("fail").unwrap().conversation_count,
        expected["state"]["conversation_count"]
    );
    m.shutdown();
    assert!(m.is_destroyed());
}
fn config(every: u32, idle: i64, delay: i64) -> PipelineConfig {
    PipelineConfig {
        every_n_conversations: every,
        enable_warmup: false,
        l1_idle_timeout_ms: idle,
        l2_delay_after_l1_ms: delay,
        l2_min_interval_ms: 0,
        l2_max_interval_ms: 3_600_000,
        session_active_window_ms: 86_400_000,
    }
}
fn msg(x: &str) -> Vec<CapturedMessage> {
    vec![CapturedMessage {
        role: "user".into(),
        content: x.into(),
        timestamp: "2026-01-01T00:00:00Z".into(),
    }]
}
fn manager(
    mode: Mode,
    cfg: PipelineConfig,
    clock: Arc<AtomicI64>,
    events: Arc<Mutex<Vec<Value>>>,
    attempts: Arc<AtomicUsize>,
) -> PipelineManager {
    PipelineManager::new(
        cfg,
        Box::new(TestClock(clock)),
        Box::new(Runner {
            mode,
            events,
            attempts,
        }),
    )
}

#[test]
fn retry_errors_preserve_buffer_and_retry_then_drain_l2() {
    let e = Arc::new(Mutex::new(vec![]));
    let n = Arc::new(AtomicUsize::new(0));
    let c = Arc::new(AtomicI64::new(1000));
    let mut m = manager(
        Mode::Retry,
        config(1, 10, 10),
        c.clone(),
        e.clone(),
        n.clone(),
    );
    m.notify_conversation("retry", msg("x"));
    for delta in [30_000, 30_000, 10] {
        c.fetch_add(delta, Ordering::SeqCst);
        m.run_due();
    }
    m.shutdown();
    assert_eq!(json!(*e.lock().unwrap()), oracle()["retry"]["events"]);
    assert_eq!(n.load(Ordering::SeqCst), oracle()["retry"]["attempts"]);
}

#[test]
fn checkpoint_recovery_runs_l2_l3_and_shutdown_drain() {
    let e = Arc::new(Mutex::new(vec![]));
    let n = Arc::new(AtomicUsize::new(0));
    let c = Arc::new(AtomicI64::new(1000));
    let mut m = manager(Mode::Recovery, config(1, 10, 5), c.clone(), e.clone(), n);
    let mut restored = HashMap::new();
    restored.insert(
        "recover".into(),
        PipelineSessionState {
            conversation_count: 2,
            last_extraction_updated_time: "cursor-old".into(),
            last_active_time: 1000,
            l2_pending_l1_count: 1,
            ..Default::default()
        },
    );
    m.start(restored);
    c.fetch_add(5, Ordering::SeqCst);
    m.run_due();
    m.shutdown();
    assert_eq!(json!(*e.lock().unwrap()), oracle()["recovery"]["events"]);
}

#[test]
fn resettable_idle_timers_keep_message_order_across_sessions() {
    let e = Arc::new(Mutex::new(vec![]));
    let n = Arc::new(AtomicUsize::new(0));
    let c = Arc::new(AtomicI64::new(1000));
    let mut m = manager(
        Mode::Interleave,
        config(99, 12, 50),
        c.clone(),
        e.clone(),
        n,
    );
    m.notify_conversation("a", msg("a1"));
    c.fetch_add(4, Ordering::SeqCst);
    m.notify_conversation("a", msg("a2"));
    c.fetch_add(2, Ordering::SeqCst);
    m.notify_conversation("b", msg("b1"));
    c.fetch_add(11, Ordering::SeqCst);
    m.run_due();
    c.fetch_add(2, Ordering::SeqCst);
    m.run_due();
    m.flush_session("b");
    m.shutdown();
    assert_eq!(json!(*e.lock().unwrap()), oracle()["interleave"]["events"]);
}
